apiVersion: apps/v1
kind: Deployment
metadata:
  name: doc-react
  labels:
    app: doc-react
spec:
  selector:
    matchLabels:
      app: doc-react
  replicas: 1
  template:
    metadata:
      name: doc-react
      labels:
        app: doc-react
    spec:
      containers:
        - name: doc-react
          image: doc-react:latest # Image that will be used inside the container in the cluster
          imagePullPolicy: Never
          ports:
            - containerPort: 3000 # The port that the container is running on in the cluster

---
apiVersion: v1
kind: Service
metadata:
  name: doc-react
  labels:
    app: doc-react
spec:
  type: NodePort
  selector:
    app: doc-react
  ports:
    - name: http
      port: 3000 # The port that the service is running on in the cluster
      targetPort: 3000