name: CD - Deploy to Minikube using Github Actions
on:
  #Trigger the workflow on push from the master/Github-Actions branch or on pull request
  push:
    branches: master
  pull_request:
    branches: master
jobs:
  # Build job
  job1:
    name: Build and Deploy to Minikube
    # Run on Ubuntu using the latest version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Start Minikube
        id: minikube
        uses: medyagh/setup-minikube@latest
      - name: Try the cluster !
        run: kubectl get pods -A
      - name: Build Image
        run: |
          export SHELL=/bin/bash
          eval $(minikube -p minikube docker-env)
          docker build -f ./Dockerfile -t devops-demo .
          docker build -f ./web/Dockerfile -t doc-react ./web
          echo -n "Verifying images: "
          docker images
      - name: Deploy to Minikube
        run: |
          kubectl apply -f web-deploy.yaml,backend-deploy.yaml
          kubectl wait --for=condition=Ready pod -l app=devops-demo
          kubectl wait --for=condition=Ready pod -l app=doc-react
          kubectl get all
      - name: Test service URLs
        run: |
          echo "SERVICE_URL=$(minikube service devops-demo --url)"
          kubectl port-forward service/devops-demo 8080:8080 &> /dev/null &
          kubectl port-forward service/doc-react 3000:3000 &> /dev/null &
          sleep 10
          kubectl port-forward service/devops-demo 8080:8080 &> /dev/null &
          kubectl port-forward service/doc-react 3000:3000 &> /dev/null &
      - run: |
          curl -i http://localhost:3000/
      - name: Cleanup
        run: |
          eval $(minikube docker-env -u)
          minikube delete